name: genminute
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - ffmpeg
  - git
  # 파이썬 패키지는 pip로 통합 관리합니다.
  # 사용법: conda env create -f environment_crossplatform.yml && pip install -r requirements.txt