-- Supabase PostgreSQL 스키마 정의
-- 기존 SQLite 구조와 최대한 호환되도록 구성 (기존 id 체계를 유지하기 위해 BIGINT IDENTITY 사용)

-- 1. users 테이블
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_id TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    profile_picture TEXT,
    role TEXT DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. meeting_dialogues 테이블 (STT 원본 텍스트 및 세그먼트)
CREATE TABLE IF NOT EXISTS public.meeting_dialogues (
    segment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id TEXT NOT NULL,
    meeting_date TEXT,
    speaker_label TEXT,
    start_time FLOAT8,
    segment TEXT,
    confidence FLOAT8,
    audio_file TEXT,
    title TEXT,
    owner_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_meeting_dialogues_meeting_id ON public.meeting_dialogues(meeting_id);
CREATE INDEX IF NOT EXISTS idx_meeting_dialogues_owner_id ON public.meeting_dialogues(owner_id);

-- 3. meeting_minutes 테이블 (회의 요약본/회의록)
CREATE TABLE IF NOT EXISTS public.meeting_minutes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id TEXT UNIQUE NOT NULL,
    title TEXT,
    meeting_date TEXT,
    minutes_content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    owner_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL
);

-- 4. meeting_mindmap 테이블 (마인드맵)
CREATE TABLE IF NOT EXISTS public.meeting_mindmap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id TEXT UNIQUE NOT NULL,
    mindmap_content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. meeting_shares 테이블 (공유 기능)
CREATE TABLE IF NOT EXISTS public.meeting_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id TEXT NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    shared_with_user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    permission TEXT DEFAULT 'read',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(meeting_id, shared_with_user_id)
);

CREATE INDEX IF NOT EXISTS idx_meeting_shares_meeting_id ON public.meeting_shares(meeting_id);

-- 6. meeting_action_items 테이블 (할 일)
CREATE TABLE IF NOT EXISTS public.meeting_action_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id TEXT NOT NULL,
    content TEXT NOT NULL,
    due_date TEXT,
    status TEXT DEFAULT 'pending',
    tool_call_id TEXT,
    calendar_event_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_action_items_meeting_id ON public.meeting_action_items(meeting_id);
